name: Tests

on: workflow_dispatch
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: Setting Up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build Current Repo
      run: go build -v ./...

    - name: Runing Test Cases for Current Repo
      run: go test -v ./...
      
    - name: Upload coverage report
      uses: paambaati/codeclimate-action@v2.7.1
      env:
        CC_TEST_REPORTER_ID: c591af7ef134a8179907e90b31c20a54c088abf769a8179256cad273a9da4f79
      with:
        coverageCommand: go test ./... -coverprofile coverage.out
        coverageLocations: ${{github.workspace}}/coverage.out
        
    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
        files: "coverage.out"

    - name: File exists
      if: steps.check_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: echo All files exists!
