name: Tests

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
      - name: Run Static Check
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1.3"
      - name: Upload coverage report to CodeClimate
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: go test ./... -coverprofile c.out
          prefix: github.com/apimatic/go-core-runtime
