name: Tests

on: workflow_dispatch
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: Setting Up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Install CodeClimate Test Reporter
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter

    - name: Run Tests with Coverage
      run: go test -v -coverprofile=coverage ./...

    - name: Upload to CodeClimate
      env:
        CC_TEST_REPORTER_ID: c591af7ef134a8179907e90b31c20a54c088abf769a8179256cad273a9da4f79
      run: |
        ./cc-test-reporter format-coverage -t gocov coverage
        ./cc-test-reporter upload-coverage
