name: Upload Coverage

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
        
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        go get -u github.com/axw/gocov/gocov
        go get -u github.com/AlekSi/gocov-xml
      
    - name: Run tests and generate coverage report
      run: |
        cd ${{ github.workspace }}
        go test -v -coverprofile=coverage.out ./... && \
        gocov convert coverage.out | gocov-xml > coverage.xml
      
    - name: Upload coverage report to CodeClimate
      uses: codeclimate/test-reporter-action@v2
      with:
        file: coverage.xml
        format: gocov
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
