name: Tests

on: workflow_dispatch
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v2

    - name: Setting Up Go Env
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Current Repo
      run: go build -v ./...

    - name: Runing Test Cases for Current Repo
      run: go test -v ./...
      
    - name: Upload coverage report
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: c591af7ef134a8179907e90b31c20a54c088abf769a8179256cad273a9da4f79
      with:
        coverageComamand: go test -v ./...
