name: Upload Coverage

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.18'
        
    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}
        go get -v github.com/axw/gocov
        go get -v github.com/AlekSi/gocov-xml
        ls -l $(go env GOPATH)/bin
      
    - name: Run tests and generate coverage report
      run: |
        cd ${{ github.workspace }}
        go test -v -coverprofile=coverage.out ./... && \
        gocov convert coverage.out | gocov-xml > coverage.xml
      
    - name: Upload coverage report to CodeClimate
      uses: paambaati/codeclimate-action@v3.0.0
      with:
        report-file: coverage.xml
        debug: true
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
